# 基础镜像
FROM nginx
# author
MAINTAINER ssrt

# 挂载目录
VOLUME /home/ssrt/projects/ssrt-ui
# 创建目录
RUN mkdir -p /home/ssrt/projects/ssrt-ui
# 指定路径
WORKDIR /home/ssrt/projects/ssrt-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/ssrt/projects/ssrt-ui
