# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER ssrt

# 挂载目录
VOLUME /home/ssrt
# 创建目录
RUN mkdir -p /home/ssrt
# 指定路径
WORKDIR /home/ssrt
# 复制jar文件到路径
COPY ./jar/ssrt-modules-file.jar /home/ssrt/ssrt-modules-file.jar
# 启动文件服务
ENTRYPOINT ["java","-jar","ssrt-modules-file.jar"]